"""
test_plot_widget.py
-------------------
pytest-qt tests for PlotWindow. Exercises data loading and close behaviour.

The HDF5 file is generated by a subprocess (`dsf run --h5`) so DSF's C
extension stays out of the Qt-loaded pytest process.
"""
import os
import glob
import subprocess
import pytest

pytestmark = pytest.mark.qt

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "../fixtures")
GPS_1HR_XML  = os.path.join(FIXTURES_DIR, "gps_1hr.xml")


@pytest.fixture(scope="module")
def h5_path(tmp_path_factory):
    """Generate a small HDF5 file once for this module via subprocess."""
    d = str(tmp_path_factory.mktemp("plot_h5"))
    before = set(glob.glob(os.path.join(d, "*.h5")))

    result = subprocess.run(
        ["dsf", "run", GPS_1HR_XML, "--h5"],
        cwd=d, capture_output=True, text=True,
    )

    after = set(glob.glob(os.path.join(d, "*.h5")))
    new   = after - before
    if not new:
        pytest.skip(f"dsf run failed: {result.stderr[:200]}")
    return max(new, key=os.path.getmtime)


@pytest.fixture
def plot_win(qtbot, h5_path):
    from dsf.gui.ui.plot_window import PlotWindow
    from dsf.utils.data_loader import load_h5
    win = PlotWindow()
    qtbot.addWidget(win)
    times, data = load_h5(h5_path)
    return win, times, data


class TestPlotWindow:

    def test_window_opens_without_crash(self, plot_win):
        win, _, _ = plot_win
        assert win is not None

    def test_has_expected_widgets(self, plot_win):
        win, _, _ = plot_win
        assert win.centralWidget() is not None or len(win.children()) > 0

    def test_close_event_does_not_crash(self, plot_win):
        win, _, _ = plot_win
        win.close()
